version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: article-summarizer-api
    ports:
      - "8000:8000"
    volumes:
      - model_cache:/app/src/models
    environment:
      - MODEL_ID=sshleifer/distilbart-cnn-12-6
      - MODEL_LOCAL_DIR=/app/src/models/bart
      - MAX_LENGTH=1024
      - MIN_LENGTH=100
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  model_cache: