name: mistral_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - pip
  - pip:
    - transformers>=4.36.0
    - tokenizers>=0.15.0
    - accelerate>=0.24.1
    - bitsandbytes>=0.41.1
    - optimum>=1.13.2
    - auto-gptq>=0.5.0
    - einops>=0.7.0
    - scipy>=1.11.3
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - streamlit==1.24.0
    - httpx==0.25.2
    - beautifulsoup4==4.12.2
    - lxml==4.9.3
    - pandas==2.1.3
    - numpy>=1.24.0
    - python-multipart==0.0.6
    - pydantic==2.5.2
    - pydantic-settings==2.1.0
    - python-dotenv>=1.0.0
    - tqdm>=4.66.1
    - ninja>=1.11.0